name: build-image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GRAALVM_VERSION: '21.3'
      JAVA_VERSION: 'java17'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GRAALVM_VERSION=${{ env.GRAALVM_VERSION }}
            JAVA_VERSION=${{ env.JAVA_VERSION }}
          tags: addozhang/graalvm-maven:${{ env.JAVA_VERSION }}-${{ env.GRAALVM_VERSION }}